import { grades, prayers, statuses, load, save, today, formatDate, studentsFor, getRecord, setStatus, advanceYear } from './store.js';
import './style.css';

let data = load();
let route = { page: 'home' };
const app = document.querySelector('#app');
const statusById = Object.fromEntries(statuses.map(s => [s.id, s]));
const esc = value => String(value).replace(/[&<>'"]/g, ch => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[ch]));
const gradeCards = (action, empty = '') => `<div class="grade-grid">${grades.map(g => `<button class="card grade-card" data-${action}="${g}"><span>RAZRED</span><strong>${g}.</strong><small>${studentsFor(data, data.activeYear, g).length} učenika</small></button>`).join('')}</div>${empty}`;
function layout(title, content, back = true) { app.innerHTML = `<main><header>${back ? '<button class="icon-btn" data-home aria-label="Početna">←</button>' : '<span></span>'}<div class="brand">EVIDENCIJA NAMAZA</div><button class="icon-btn" data-settings aria-label="Postavke">⚙</button></header><section class="page"><div class="eyebrow">${data.activeYear}</div><h1>${title}</h1>${content}</section></main>`; wireCommon(); }
function wireCommon() { document.querySelectorAll('[data-home]').forEach(x=>x.onclick=()=>render({page:'home'})); document.querySelectorAll('[data-settings]').forEach(x=>x.onclick=()=>render({page:'settings'})); }
function render(next = route) { route = next; const { page } = route; if (page === 'home') return home(); if(page === 'prayerGrades') return prayerGrades(); if(page === 'rollcall') return rollcall(); if(page === 'summary') return summary(); if(page === 'students') return studentGrades(); if(page === 'studentList') return studentList(); if(page === 'history') return history(); if(page === 'records') return records(); if(page === 'settings') return settings(); }
function home() { layout('Dobro došli', `<p class="date">${formatDate(today())}</p><div class="prayer-grid">${prayers.map(p=>`<button class="prayer" data-prayer="${p.id}">${p.label.toUpperCase()}</button>`).join('')}</div><div class="nav-grid"><button data-records>EVIDENCIJA</button><button data-students>UČENICI</button><button data-settings>POSTAVKE</button></div>`, false); document.querySelectorAll('[data-prayer]').forEach(b=>b.onclick=()=>render({page:'prayerGrades', prayer:b.dataset.prayer})); document.querySelector('[data-records]').onclick=()=>render({page:'records'}); document.querySelector('[data-students]').onclick=()=>render({page:'students'}); }
function prayerGrades() { const p=prayers.find(x=>x.id===route.prayer); layout(p.label.toUpperCase(), `<p class="lead">Odaberite razred za prozivku.</p>${gradeCards('grade')}`); document.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>render({page:'rollcall', prayer:route.prayer, grade:+b.dataset.grade, index:0, date:today()})); }
function rollcall() { const {prayer,grade,date}=route, list=studentsFor(data,data.activeYear,grade); if (!list.length) return layout(`${grade}. RAZRED`, '<div class="empty">U ovom razredu nema aktivnih učenika.</div>'); const index=Math.min(route.index,list.length-1), student=list[index], selected=getRecord(data,date,student.id)?.statuses[prayer]; const p=prayers.find(x=>x.id===prayer); layout(`${p.label.toUpperCase()} — ${grade}. RAZRED`, `<div class="call-date"><input id="call-date" type="date" value="${date}"></div><div class="progress"><span>${index + 1} / ${list.length} učenika</span><div><i style="width:${((index+1)/list.length)*100}%"></i></div></div><article class="student-focus"><span>UČENIK</span><h2>${esc(student.name)}</h2></article><div class="status-grid">${statuses.map(s=>`<button class="status ${s.className} ${selected===s.id?'chosen':''}" data-status="${s.id}">${s.label.toUpperCase()} ${selected===s.id?'✓':''}</button>`).join('')}</div><p class="saved" id="saved">${selected?'Prethodno sačuvano ✓':''}</p><div class="pager"><button data-prev ${index===0?'disabled':''}>← PRETHODNI</button><button data-next>${index===list.length-1?'ZAVRŠI':'SLJEDEĆI →'}</button></div>`); document.querySelector('#call-date').onchange=e=>render({...route,date:e.target.value,index:0}); document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{setStatus(data,date,student.id,prayer,b.dataset.status); document.querySelector('#saved').textContent='Sačuvano ✓'; setTimeout(()=> render(index===list.length-1?{...route,index}:{...route,index:index+1}),260);}); document.querySelector('[data-prev]').onclick=()=>render({...route,index:index-1}); document.querySelector('[data-next]').onclick=()=>render(index===list.length-1?{page:'summary',prayer,grade,date}:{...route,index:index+1}); }
function summary() { const {prayer,grade,date}=route,list=studentsFor(data,data.activeYear,grade), counts=Object.fromEntries(statuses.map(s=>[s.id,0])); list.forEach(s=>{const z=getRecord(data,date,s.id)?.statuses[prayer];if(z)counts[z]++}); const p=prayers.find(x=>x.id===prayer); layout(`${grade}. RAZRED — ${p.label.toUpperCase()}`, `<p class="date">${formatDate(date)}</p><div class="summary"><strong>Ukupno: ${list.length}</strong>${statuses.map(s=>`<p><span class="dot ${s.className}"></span>${s.label}: <b>${counts[s.id]}</b></p>`).join('')}</div><div class="nav-grid two"><button data-next-grade>SLJEDEĆI RAZRED</button><button data-home>POČETNA</button></div>`); document.querySelector('[data-next-grade]').onclick=()=>grade<4?render({page:'rollcall',prayer,grade:grade+1,index:0,date}):render({page:'home'}); }
function studentGrades(){ layout('Učenici', '<p class="lead">Odaberite razred.</p>'+gradeCards('student-grade')); document.querySelectorAll('[data-student-grade]').forEach(b=>b.onclick=()=>render({page:'studentList',grade:+b.dataset.studentGrade})); }
function studentList(){ const list=studentsFor(data,data.activeYear,route.grade); layout(`${route.grade}. RAZRED — UČENICI`, `<button class="add" data-add>＋ DODAJ UČENIKA</button><ol class="student-list">${list.map(s=>`<li><button data-history="${s.id}">${esc(s.name)}</button><span><button data-edit="${s.id}" aria-label="Uredi">✎</button><button data-remove="${s.id}" aria-label="Ukloni">×</button></span></li>`).join('')||'<li class="empty">Nema učenika.</li>'}</ol>`); document.querySelector('[data-add]').onclick=()=>{const name=prompt('Ime i prezime učenika:');if(name?.trim()){data.students.push({id:crypto.randomUUID(),name:name.trim(),grade:route.grade,year:data.activeYear,active:true});save(data);render()}}; document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{let s=data.students.find(x=>x.id===b.dataset.edit),n=prompt('Uredi ime:',s.name);if(n?.trim()){s.name=n.trim();save(data);render()}}); document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{if(confirm('Ukloniti učenika?')){data.students.find(x=>x.id===b.dataset.remove).active=false;save(data);render()}}); document.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>render({page:'history',studentId:b.dataset.history})); }
function history(){const s=data.students.find(x=>x.id===route.studentId), rows=data.records.filter(r=>r.studentId===s.id).sort((a,b)=>b.date.localeCompare(a.date)); layout(s.name, `<p class="lead">Historija prisustva</p><div class="table-wrap"><table><thead><tr><th>Datum</th><th>Razred</th>${prayers.map(p=>`<th>${p.label}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><td>${formatDate(r.date)}</td><td>${s.grade}.</td>${prayers.map(p=>`<td>${r.statuses[p.id]||'—'}</td>`).join('')}</tr>`).join('')||'<tr><td colspan="7">Još nema evidencije.</td></tr>'}</tbody></table></div>`);}
function records(){const selectedYear=route.year||data.activeYear,grade=route.grade||1,date=route.date||today(),list=studentsFor(data,selectedYear,grade); layout('Evidencija', `<div class="filters"><label>Školska godina<select id="year">${data.years.map(y=>`<option ${y===selectedYear?'selected':''}>${y}</option>`)}</select></label><label>Razred<select id="grade">${grades.map(g=>`<option value="${g}" ${g===grade?'selected':''}>${g}. razred</option>`)}</select></label><label>Datum<input id="record-date" type="date" value="${date}"></label></div><button class="export" data-export>⇩ IZVEZI U EXCEL</button><div class="table-wrap"><table><thead><tr><th>Učenik</th>${prayers.map(p=>`<th>${p.label}</th>`).join('')}</tr></thead><tbody>${list.map(s=>{const r=getRecord(data,date,s.id);return `<tr><td><button class="table-name" data-history="${s.id}">${esc(s.name)}</button></td>${prayers.map(p=>`<td>${r?.statuses[p.id]||'—'}</td>`).join('')}</tr>`}).join('')||'<tr><td colspan="6">Nema učenika.</td></tr>'}</tbody></table></div>`); ['year','grade','record-date'].forEach(id=>document.querySelector('#'+id).onchange=()=>render({page:'records',year:document.querySelector('#year').value,grade:+document.querySelector('#grade').value,date:document.querySelector('#record-date').value})); document.querySelector('[data-export]').onclick=()=>exportXlsx(list,selectedYear,grade,date); document.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>render({page:'history',studentId:b.dataset.history}));}
function crc32(bytes){let c=~0;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(~c)>>>0}
function xlsxZip(files){const enc=new TextEncoder(),parts=[],central=[];let offset=0;const u16=n=>[n&255,n>>>8&255],u32=n=>[n&255,n>>>8&255,n>>>16&255,n>>>24&255];for(const [name,body] of files){const n=enc.encode(name),b=enc.encode(body),crc=crc32(b),local=new Uint8Array([80,75,3,4,20,0,0,0,0,0,0,0,0,0,...u32(crc),...u32(b.length),...u32(b.length),...u16(n.length),0,0,...n,...b]);parts.push(local);central.push(new Uint8Array([80,75,1,2,20,0,20,0,0,0,0,0,0,0,0,0,...u32(crc),...u32(b.length),...u32(b.length),...u16(n.length),0,0,0,0,0,0,0,0,0,0,0,0,...u32(offset),...n]));offset+=local.length}const center=central.reduce((a,b)=>a+b.length,0),end=new Uint8Array([80,75,5,6,0,0,0,0,...u16(files.length),...u16(files.length),...u32(center),...u32(offset),0,0]);return new Blob([...parts,...central,end],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}
function exportXlsx(list,year,grade,date){const xml=v=>esc(v).replace(/&quot;/g,'&quot;'), cells=(values,row)=>values.map((v,i)=>`<c r="${String.fromCharCode(65+i)}${row}" t="inlineStr"><is><t>${xml(v)}</t></is></c>`).join('');const rows=[['Učenik',...prayers.map(p=>p.label)],...list.map(s=>{const r=getRecord(data,date,s.id);return[s.name,...prayers.map(p=>r?.statuses[p.id]||'')]})];const sheet=`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${rows.map((r,i)=>`<row r="${i+1}">${cells(r,i+1)}</row>`).join('')}</sheetData></worksheet>`;const files=[['[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'],['_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],['xl/workbook.xml','<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Evidencija" sheetId="1" r:id="rId1"/></sheets></workbook>'],['xl/_rels/workbook.xml.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'],['xl/worksheets/sheet1.xml',sheet]];const a=document.createElement('a');a.href=URL.createObjectURL(xlsxZip(files));a.download=`evidencija-${year.replace('/','-')}-${grade}-razred-${date}.xlsx`;a.click();URL.revokeObjectURL(a.href)}
function settings(){layout('Postavke', `<section class="setting"><h2>Školska godina</h2><p>Aktivna školska godina: <b>${data.activeYear}</b></p><button data-advance>NOVA ŠKOLSKA GODINA</button><p class="hint">Učenici će automatski preći u sljedeći razred. Učenici 4. razreda završavaju školovanje.</p></section>`);document.querySelector('[data-advance]').onclick=()=>{if(confirm('Pokrenuti novu školsku godinu?')){advanceYear(data);render({page:'home'})}}}
render();
